version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8091:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3309:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=IT4492
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=request_gate
      - PMA_PASSWORD=request_gate
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /sessions
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
